### ISSUE TITLE
Can't run Mariana Trench on M1

### ISSUE THREAD

**Issue by Tihan-Nico** [facebook/mariana-trench#69] opened 2021-11-14 00:12 UTC
# Bug
**Bug description**
When I try to run Mariana Trench I keep getting this error for some reason. I've even tried running the sample application from the repo and the problem keeps persisting. Is there anyway around it or am I doing something wrong?

**Logs**
```
CRITICAL Unexpected error:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/mariana_trench/shim/shim.py", line 583, in main
    output = subprocess.run(command)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/opt/homebrew/bin/mariana-trench-binary'
```

**Comment by arthaud** [comment] 2021-11-15 18:10
Duplicate of #49

**Closed by arthaud** 2021-11-15 18:10 UTC
